### ISSUE TITLE
RNA sequences

### ISSUE THREAD

**Issue by piia600** [phglab/ALFATClust#5]
Hi,

Thanks for the clustering tool, it seems to work nicely for my purposes. I don't exactly have an issue to report, since all my usage issues were due to my own stupidity. However, I am also dealing with RNA sequences. It is not a big deal to replace all the U with T in a text editor, but is there any plan on making this work on RNA as well? :)

Best regards from Finland,
Piia

**Comment by jimmykhchiu** [comment]
Hi @piia600 , I uploaded a utility (under subdirectory `utils` in `main`) to convert RNA sequences to DNA sequences through reverse transcription. So now you may cluster your RNA sequences via the converted DNA sequences.
